export const ErrNetworkErr = 'network error'

export const ErrRequiredUserID = 'required user id'
export const ErrRequiredUserUsername = 'required username'
export const ErrUserAlreadyExists = 'username already taken'
export const ErrRequiredFirstName = 'required first name'
export const ErrRequiredLastName = 'required last name'
export const ErrRequiredUserPassword = 'required password'
export const ErrUserNotFound = 'user not found'
export const ErrIncorrectPassword = 'incorrect password'
export const ErrUserUnauthorized = 'unauthorized'
export const ErrUserForbidden = 'forbidden'

export const ErrRequiredFolderID = 'required folder id'
export const ErrFolderNotFound = 'folder not found'
export const ErrFolderAlreadyExists = 'folder already exists'
export const ErrRequiredFolderName = 'required folder name'
export const ErrRequiredLastEditorID = 'required last editor id'
export const ErrFolderNotEmpty = 'cannot delete non-empty folder'
export const ErrRequiredParentFolderID = 'required parent folder id'
export const ErrInvalidParentFolderID = 'invalid parent folder id'

export const ErrRequiredUserRoleName = 'required user role name'
export const ErrRequiredUserRoleID = 'required user role id'
export const ErrUserRoleNotFound = 'user role not found'
export const ErrUserRoleAlreadyExists = 'user role already exists'

export const ErrInvalidAccessLevel = 'invalid access level'
export const ErrRequiredAccessLevel = 'required access level'
export const ErrRequiredAccessRoleID = 'required access role id'
export const ErrAccessRoleNotFound = 'access role not found'
export const ErrAccessRoleAlreadyExists = 'access role already exists'
